baseURL = "https://soukaina-ouakka.com"
disableLanguages = []
disqusShortname = "Kross"
googleAnalytics = ""
hasCJKLanguage = false
paginate = "6"
summaryLength = "10"
theme = ["kross-hugo"]
timeZone = "UTC"
title = "SOUKAINA-OUAKKA"
[build]
writeStats = true
[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"
[imaging]
quality = 90
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = "monokai"
[markup.tableOfContents]
endLevel = 5
ordered = true
startLevel = 2
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]
[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
[outputs]
home = ["HTML", "RSS", "WebAppManifest"]
