contact_form_action = "#"
copyright = "Copyright by SOUKAINA OUAKKA"
custom_script = ""
favicon = "images/favicon.png"
google_adsense = ""
google_tag_manager = ""
logo = ""
logo_text = "Kross"
logo_webp = true
logo_width = ""
mainSections = ["blog"]
navbar_fixed = false
purge_css = true
search = true
theme_color = "#41228e"
theme_copyright = true
[baidu]
analytics_id = ""
enable = false
[contact_info]
address = "Île-de-France"
email = "Soukaina-ouakka@outlook.fr"
mobile = "(+33) 7 83 49 30 15"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[counter]
enable = false
username = ""
[crisp_chat]
crisp_website_id = "9aa449e1-9999-422a-938f-8567982eec6d"
enable = false
[google_map]
enable = true
[matomo]
enable = false
id = ""
url = ""
[metadata]
author = "Themefisher"
description = "This is meta description"
image = "images/favicon.png"
keywords = ["Boilerplate", "Hugo", "Themefisher", "GetHugoThemes"]
[plausible]
domain = ""
enable = false
[preloader]
enable = true
preloader = "images/preloader.gif"
[site_verification]
baidu = ""
bing = ""
facebook = ""
google = ""
mastodon = ""
[subscription]
enable = false
mailchimp_form_action = "https://app.us21.list-manage.com/subscribe/post?u=6b8e647c4b5e5ebca6efed832&amp;id=4c5548aaa6&amp;f_id=008e8ae1f0"
mailchimp_form_name = "b_6b8e647c4b5e5ebca6efed832_4c5548aaa6"
[valine_comment]
appId = ""
appKey = ""
avatar = ""
enable = false
enableQQ = false
highlight = true
pageSize = 10
recordIP = true
visitor = true
[widgets]
sidebar = ["search", "categories", "tags", "recent-post"]
[[logo_slider]]
URL = "http://examplesite.com"
logo = "images/clients-logo/client-logo-1.png"
[[logo_slider]]
URL = "#"
logo = "images/clients-logo/client-logo-2.png"
[[logo_slider]]
URL = "http://examplesite.com"
logo = "images/clients-logo/client-logo-3.png"
[[logo_slider]]
URL = "#"
logo = "images/clients-logo/client-logo-4.png"
[[logo_slider]]
URL = "http://examplesite.com"
logo = "images/clients-logo/client-logo-5.png"
[[logo_slider]]
URL = "#"
logo = "images/clients-logo/client-logo-1.png"
[[logo_slider]]
URL = "http://examplesite.com"
logo = "images/clients-logo/client-logo-2.png"
[[logo_slider]]
URL = "#"
logo = "images/clients-logo/client-logo-3.png"
[[logo_slider]]
URL = "http://examplesite.com"
logo = "images/clients-logo/client-logo-4.png"
[[logo_slider]]
URL = "#"
logo = "images/clients-logo/client-logo-5.png"
[[social]]
icon = "ti-twitter"
link = "#"
title = "twitter"
[[social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/in/soukaina-ouakka"
title = "linkedin"
